"""empty message

Revision ID: 729571373694
Revises: 7e22462193b5
Create Date: 2022-04-09 19:49:19.268162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '729571373694'
down_revision = '7e22462193b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('user', 'data_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
